---
title: "채널 트래픽 분석"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      fg: "#605CA8"
      bg: "#FDF7F7"
      primary: "#605CA8"
      navbar-bg: "#3ADAC6"
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(magrittr)
library(ggthemes)
library(plotly)
```


```{r userdefine-functions, include=FALSE}
##------------------------------------------------------------------------------
## Read data from CSV
##------------------------------------------------------------------------------
audience <- read.csv("data/daily_traffic.csv")
hits <- read.csv("data/daily_hits.csv")

##------------------------------------------------------------------------------
# Change from second to HMS
##------------------------------------------------------------------------------
sec2hms <- function(x) {
  x <- round(x) |> 
    lubridate::seconds_to_period()
  
  sprintf('%02d:%02d:%02d', x@hour, lubridate::minute(x), 
          lubridate::second(x))
}

##------------------------------------------------------------------------------
## Create visualization theme
##------------------------------------------------------------------------------
create_theme <- function(family = "NanumSquare", no_axis = FALSE, 
                         no_grid = FALSE, no_grid_x = FALSE, 
                         fill = c("beige", "blue-gray", "dark blue-gray", 
                                  "light gray", "white")[1]) {
  fill = switch (
    fill, beige = "#f9f5f1", "blue-gray" = "#d5e4eb", 
    "dark blue-gray" = "#c3d6df", "light gray" = "#ebebeb", white = "#ffffff"
  )
  
  theme_custom <- theme_economist(base_family = family) +
    theme(
      text = element_text(family = family),
      rect = element_rect(fill = fill),
      plot.background = element_rect(fill = fill),
      strip.background.y = element_rect(fill = "#857670"),
      strip.text = element_text(colour = "white"),
      panel.grid.major.y = element_line(colour = "white", size = 0.6)
    )
  
  if (no_grid_x) {
    theme_custom <- theme_custom +
      theme( panel.grid.major.x = element_blank() )  
  } else {
    theme_custom <- theme_custom +
      theme( panel.grid.major.x = element_line(colour = "white", size = 0.6) )  
  }
  
  if (no_axis) {
    theme_custom <- theme_custom +
      theme(
        axis.text = element_blank(),
        axis.line.x = element_blank(),
        axis.title = element_blank(), 
        axis.ticks = element_blank()
      )
  }
  
  if (no_grid) {
    theme_custom <- theme_custom +
      theme(
        panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
      )
  }
  
  theme_custom
}

# Font family
font_family <- "NanumSquare"

theme_mine <- create_theme(family = font_family, no_grid_x = TRUE)

##------------------------------------------------------------------------------
## Trend plot using ggplotly
##------------------------------------------------------------------------------
trend_plotly <- function(x, y, main = NULL, sub = NULL, xlim = NULL) {
  trend <- data.frame(date = as.Date(x), value = y)
  
  if (is.null(xlim)) {
    date_min <- min(trend$date)
    date_max <- max(trend$date)
  } else {
    date_min <- as.Date(xlim[1])
    date_max <- as.Date(xlim[2])    
  }
  
  datebreaks <- seq(date_min, date_max, by = 15)
  
  p <- trend |> 
    filter(date >= date_min & date <= date_max) |> 
    ggplot(aes(x = date, y = value, group = 1, text = paste(
      "Date: ", date, "\n",
      "Value: ", format(round(value), big.mark = ","), "\n", sep = ""
    ))) + 
    theme(legend.title = element_blank(), legend.position = "top") +
    geom_line(stat = "identity") + 
    stat_smooth(method = loess, formula = y ~ x) + 
    scale_x_date(breaks = datebreaks) +
    labs(x = "일자", y = NULL) + 
    ggtitle(main, subtitle = sub) + 
    theme_bw() + 
    theme_mine 
  
  ctext <- "\nSource: GA4 Log Data\nVisualization Powered by dpxReport"
  ggplotly(p, tooltip = "text", dynamicTicks = FALSE) |> 
    layout(title = list(
      text = paste0(main, '<br>', '<sup>', sub, '</sup>'))
    )
}

##------------------------------------------------------------------------------
## Get data from data.fromes - for Audience-top frow
##------------------------------------------------------------------------------
get_audience_metric <- function(metric, sdate, edate) {
  tabs <- audience |> 
      filter(date >= sdate) |>       
      filter(date <= edate) 
  
  if (metric %in% c("n_user", "n_session", "n_screen")) {
    tabs |> 
      select(all_of(paste0(metric, "_d1"))) |> 
      pull() |> 
      sum()
  } else if (metric %in% c("derived_screen_per_session")) {
    tabs |> 
      summarise(round(sum(n_screen_d1) / sum(n_session_d1), 2)) |> 
      pull()
  } else if (metric %in% c("derived_avg_duration")) {
    tabs |> 
      summarise(sum(tot_timeonsite_d1) / sum(n_session_d1)) |> 
      pull()
  } else if (metric %in% c("derived_pct_newsession")) {
    tabs |> 
      summarise(round(sum(n_newsession_d1) / sum(n_session_d1) * 100, 2)) |> 
      pull()
  }
}

##------------------------------------------------------------------------------
## Get data from data.fromes - for Audience-bottom frow
##------------------------------------------------------------------------------
get_audience_trend <- function(metric) {
  if (metric %in% c("n_user_d1", "n_session_d1", "n_screen_d1")) {
    audience |> 
      select(date, all_of(metric)) |> 
      group_by(date) |> 
      summarize_all(list(sum))
  } else if (metric %in% c("screen_per_session")) {
    audience |> 
      group_by(date) |> 
      summarise(screen_per_session = 
                  round(sum(n_screen_d1) / sum(n_session_d1), 2))
  } else if (metric %in% c("avg_duration")) {
    audience |> 
      group_by(date) |> 
      summarise(avg_duration = 
                  sum(tot_timeonsite_d1) / sum(n_session_d1))
  } else if (metric %in% c("pct_newsession")) {
    audience |> 
      group_by(date) |> 
      summarise(pct_newsession = 
                  round(sum(n_newsession_d1) / sum(n_session_d1) * 100, 2))
  }
}

##------------------------------------------------------------------------------
## Get data from data.fromes - for Behavior-top frow
##------------------------------------------------------------------------------
get_behavior_metric <- function(metric) {
  if (metric %in% c("n_screen", "n_event", "n_crash")) {
    hits |> 
      select(all_of(metric)) |> 
      pull() |> 
      sum()
  } else if (metric %in% c("screen_per_session")) {
    hits |> 
      summarise(round(sum(n_screen) / sum(n_session), 2)) |> 
      pull()
  } else if (metric %in% c("avg_duration")) {
    hits |> 
      summarise(sum(tot_duration) / sum(n_duration)) |> 
      pull()
  }
}

##------------------------------------------------------------------------------
## Get data from data.fromes - for Behavior-bottom frow
##------------------------------------------------------------------------------
get_screen_list <- function() {
  hits |> 
    group_by(screen_name) |>     
    summarize(n_screen = sum(n_screen, na.rm = TRUE),
              avg_duration = round(sum(tot_duration, na.rm = TRUE) / 
                                     sum(n_duration, na.rm = TRUE)),
              screen_per_session = round(mean(screen_per_session, na.rm = TRUE), 1),
              n_exit = sum(n_exit, na.rm = TRUE),
              .groups = "drop") |>     
    mutate(pct_screen = round(n_screen / sum(n_screen) * 100, 2)) |> 
    mutate(avg_duration = sec2hms(ifelse(is.finite(avg_duration), avg_duration, 
                                         0))) |> 
    arrange(desc(n_screen)) |> 
    select("화면 이름" = screen_name,
           "조회수" = n_screen,
           "조회 비율(%)" = pct_screen,
           "평균화면시간" = avg_duration,
           "세션당 조회수" = screen_per_session,
           "이탈수" = n_exit) |> 
    head(n = 100)
}  
```


```{css}
.value-box .value {
    color: white;
}

.value-box .caption {
    color: white;
}

.nav-tabs-custom > .nav-tabs > li.active > a, .nav-tabs-custom > .nav-tabs > li.active:hover > a {
    background-color: #FDF7F7;
    color: #000000;
    font-weight: 500;
}
```


Audience Indicator {data-icon="fa-user"}
=====================================  

Row {data-width=100}
-------------------------------------

### 사용자수

```{r}
valueBox(formatC(get_audience_metric("n_user", "2021-01-01", "2021-01-31"), format = "d", big.mark = ","), 
         caption = "사용자수", color = "#3C8DBC", icon = "fa-users")
```

### 세션수

```{r}
valueBox(formatC(get_audience_metric("n_session", "2021-01-01", "2021-01-31"), format = "d", big.mark = ","), 
         caption = "세션수", color = "#3C8DBC", icon = "fa-comments")
```

### 화면뷰

```{r}
valueBox(formatC(get_audience_metric("n_screen", "2021-01-01", "2021-01-31"), format = "d", big.mark = ","), 
         caption = "화면뷰", color = "#3C8DBC", icon = "fa-desktop")
```


Row {data-width=100}
-------------------------------------

### 세션당 화면뷰

```{r}
valueBox(formatC(get_audience_metric("derived_screen_per_session", "2021-01-01", "2021-01-31"), 
                 format = "f", digits = 2),
                 caption = "세션당 화면뷰", color = "#3D9970", icon = "fa-image")
```

### 평균 세션시간

```{r}
valueBox(formatC(get_audience_metric("derived_avg_duration", "2021-01-01", "2021-01-31") |> sec2hms(), 
                 format = "s"), 
         caption = "평균 세션시간", color = "#3D9970", icon = "fa-hourglass")
```

### %신규 세션

```{r}
valueBox(paste(formatC(get_audience_metric("derived_pct_newsession", "2021-01-01", "2021-01-31"), 
                       format = "f", digits = 2), "%", sep = ""), 
        caption = "%신규 세션", color = "#3D9970", icon = "fa-plus")
```


Row {.tabset .tabset-fade}
-------------------------------------
   
### 사용자수
    
```{r}
get_audience_trend("n_user_d1") %$% 
  trend_plotly(date, n_user_d1, "사용자수 트랜드", "일별 접속 사용자 수")
```

### 세션수
    
```{r}
get_audience_trend("n_session_d1") %$% 
  trend_plotly(date, n_session_d1, "세션수 트랜드", "세션수")
```

### 화면뷰수

```{r}
get_audience_trend("n_screen_d1") %$% 
  trend_plotly(date, n_screen_d1, "화면뷰 트랜드", "일별 화면뷰수")
```

### 세션당 화면뷰수

```{r}
get_audience_trend("screen_per_session") %$% 
  trend_plotly(date, screen_per_session, "세션당 화면뷰 트랜드", "일별 세션당 화면뷰수")
```

### 평균 세션시간

```{r}
get_audience_trend("avg_duration") %$% 
  trend_plotly(date, avg_duration, "평균 세션시간 트랜드", "일별 평균 세션시간 (단위:초)")
```

### 신규세션 비율

```{r}
get_audience_trend("pct_newsession") %$% 
  trend_plotly(date, pct_newsession, "신규 세션 비율 트랜드", "일별 신규세션 비율 (%)")
```

Behavior Indicator {data-icon="fa-route"}
=====================================  

Row {data-width=100}
-------------------------------------

### 화면/페이지 뷰

```{r}
valueBox(formatC(get_behavior_metric("n_screen"), format = "d", big.mark = ","), 
         caption = "화면/페이지 뷰", color = "#3C8DBC", icon = "fa-desktop")
```

### 평균 화면/페이지 시간

```{r}
valueBox(formatC(get_behavior_metric("avg_duration") |>  sec2hms(), format = "s"), 
         caption = "평균 화면/페이지 시간", color = "#3C8DBC", icon = "fa-image")
```

### 세션당 화면/페이지 뷰

```{r}
valueBox(formatC(get_behavior_metric("screen_per_session"), format = "f", digits = 2), 
         caption = "세션당 화면/페이지 뷰", color = "#3C8DBC", icon = "fa-hourglass")
```


Row {.tabset .tabset-fade}
-------------------------------------
   
### 화면 조회 현황

```{r}
DT::datatable(
  get_screen_list(),
  options = list(
    lengthMenu = list(c(5, 10, 15, -1), c('5', '10', '15', 'All')),
    pageLength = 10
  )
) |> 
  DT::formatCurrency(c("조회수", "이탈수"), currency = "", interval = 3, 
                 mark = ",", digits = 0)  
```


